from decimal import Decimal

FORMULA_VERSION = "fair-price-rules-v1"
CURRENCY = "INR"

DEFAULT_COMPARABLE_INFLUENCE = Decimal("20")
DEFAULT_MAX_ADJUSTMENT = Decimal("10")
DEFAULT_FRESHNESS_DAYS = 180
DEFAULT_LOW_BUFFER = Decimal("5")
DEFAULT_HIGH_BUFFER = Decimal("10")

SUPPORTED_LOCALES = frozenset({"en", "hi", "or", "bn"})

MAX_REASONABLE_VALUE = Decimal("100000000")
MAX_REASONABLE_QUANTITY = Decimal("1000000")
MAX_REASONABLE_HOURS = Decimal("100000")
MAX_REASONABLE_RATE = Decimal("1000000")
